FROM kernel-module:latest as module
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y wireguard nano iproute2 && \
    apt-get autoremove --purge && \
    apt-get -y clean && \
    rm -rf /var/lib/apt/lists/*

CMD ["sleep", "infinity"]

COPY --from=module /wireguard.ko /wireguard.ko
COPY wg0.conf /etc/wireguard/
